trigger: none
  # branches:
  #   include:
  #   - feature/*
  #   exclude:
  #     - main


parameters:
- name: environment
  type: string
  default: dev
  values:
    - dev
    - qa
    - prod





pool: Remote_Agent




variables:
- name: TF_WORKDIR
  value: '$(System.DefaultWorkingDirectory)/env'



stages:
  - stage: Terraformbuild
    jobs:
      - job: Terraformbuild
        steps:
        - task: DownloadSecureFile@1
          name: terraformtfvars
          inputs:
            secureFile: '${{ parameters.environment }}.tfvars'
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script:
              # Write your commands here
              # echo 'Copy TFVARS'
              cp "$(terraformtfvars.secureFilePath)" "$(TF_WORKDIR)/${{ parameters.environment }}"
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'aniket'
            backendAzureRmStorageAccountName: 'backendstg03'
            workingDirectory: '$(TF_WORKDIR)/${{ parameters.environment }}'
            backendAzureRmContainerName: 'aniket'
            backendAzureRmKey: 'dev.tfstate'
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '''$(TF_WORKDIR)/${{ parameters.environment }}'''
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(TF_WORKDIR)/${{ parameters.environment }}'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            workingDirectory: '$(TF_WORKDIR)/${{ parameters.environment }}'
            command: 'plan'
            environmentServiceNameAzureRM: 'aniket'


