
trigger: none
  # branches:
  #   include:
  #   - main
  #   - feature/*

pool: Remote_Agent

stages:
  - stage: Terraformbuild
    jobs:
      - job: Terraformbuild
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'aniket'
            backendAzureRmStorageAccountName: 'backendstg03'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendAzureRmContainerName: 'aniket'
            backendAzureRmKey: 'dev.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
